package web

import (
	"bytes"
	"encoding/csv"
	"fmt"
	"strings"
	"time"
)

func (rg *ReportGenerator) ExportToCSV(report *ComprehensiveReport) ([]byte, error) {
	var buf bytes.Buffer
	writer := csv.NewWriter(&buf)

	// Write header section
	_ = writer.Write([]string{"K13d Cluster Report"})
	_ = writer.Write([]string{"Generated At:", report.GeneratedAt.Format(time.RFC3339)})
	_ = writer.Write([]string{"Generated By:", report.GeneratedBy})
	_ = writer.Write([]string{"Health Score:", fmt.Sprintf("%.1f%%", report.HealthScore)})
	_ = writer.Write([]string{""})

	// Cluster Summary
	_ = writer.Write([]string{"=== CLUSTER SUMMARY ==="})
	_ = writer.Write([]string{"Metric", "Value"})
	_ = writer.Write([]string{"Total Nodes", fmt.Sprintf("%d", report.NodeSummary.Total)})
	_ = writer.Write([]string{"Ready Nodes", fmt.Sprintf("%d", report.NodeSummary.Ready)})
	_ = writer.Write([]string{"Total Pods", fmt.Sprintf("%d", report.Workloads.TotalPods)})
	_ = writer.Write([]string{"Running Pods", fmt.Sprintf("%d", report.Workloads.RunningPods)})
	_ = writer.Write([]string{"Pending Pods", fmt.Sprintf("%d", report.Workloads.PendingPods)})
	_ = writer.Write([]string{"Failed Pods", fmt.Sprintf("%d", report.Workloads.FailedPods)})
	_ = writer.Write([]string{"Total Deployments", fmt.Sprintf("%d", report.Workloads.TotalDeployments)})
	_ = writer.Write([]string{"Healthy Deployments", fmt.Sprintf("%d", report.Workloads.HealthyDeploys)})
	_ = writer.Write([]string{"Total Services", fmt.Sprintf("%d", report.Workloads.TotalServices)})
	_ = writer.Write([]string{""})

	// Nodes
	_ = writer.Write([]string{"=== NODES ==="})
	_ = writer.Write([]string{"Name", "Status", "Roles", "Version", "CPU", "Memory", "IP"})
	for _, node := range report.Nodes {
		_ = writer.Write([]string{
			node.Name,
			node.Status,
			strings.Join(node.Roles, ","),
			node.KubeletVersion,
			node.CPUCapacity,
			node.MemoryCapacity,
			node.InternalIP,
		})
	}
	_ = writer.Write([]string{""})

	// Namespaces
	_ = writer.Write([]string{"=== NAMESPACES ==="})
	_ = writer.Write([]string{"Name", "Status", "Pods", "Deployments", "Services"})
	for _, ns := range report.Namespaces {
		_ = writer.Write([]string{
			ns.Name,
			ns.Status,
			fmt.Sprintf("%d", ns.PodCount),
			fmt.Sprintf("%d", ns.DeployCount),
			fmt.Sprintf("%d", ns.ServiceCount),
		})
	}
	_ = writer.Write([]string{""})

	// Pods
	_ = writer.Write([]string{"=== PODS ==="})
	_ = writer.Write([]string{"Name", "Namespace", "Status", "Ready", "Restarts", "Node", "IP", "Age"})
	for _, pod := range report.Pods {
		_ = writer.Write([]string{
			pod.Name,
			pod.Namespace,
			pod.Status,
			pod.Ready,
			fmt.Sprintf("%d", pod.Restarts),
			pod.Node,
			pod.IP,
			pod.Age,
		})
	}
	_ = writer.Write([]string{""})

	// Deployments
	_ = writer.Write([]string{"=== DEPLOYMENTS ==="})
	_ = writer.Write([]string{"Name", "Namespace", "Ready", "Up-to-date", "Available", "Strategy", "Age"})
	for _, dep := range report.Deployments {
		_ = writer.Write([]string{
			dep.Name,
			dep.Namespace,
			dep.Ready,
			fmt.Sprintf("%d", dep.UpToDate),
			fmt.Sprintf("%d", dep.Available),
			dep.Strategy,
			dep.Age,
		})
	}
	_ = writer.Write([]string{""})

	// Services
	_ = writer.Write([]string{"=== SERVICES ==="})
	_ = writer.Write([]string{"Name", "Namespace", "Type", "ClusterIP", "ExternalIP", "Ports", "Age"})
	for _, svc := range report.Services {
		_ = writer.Write([]string{
			svc.Name,
			svc.Namespace,
			svc.Type,
			svc.ClusterIP,
			svc.ExternalIP,
			svc.Ports,
			svc.Age,
		})
	}
	_ = writer.Write([]string{""})

	// Images
	_ = writer.Write([]string{"=== CONTAINER IMAGES ==="})
	_ = writer.Write([]string{"Image", "Repository", "Tag", "Pod Count"})
	for _, img := range report.Images {
		_ = writer.Write([]string{
			img.Image,
			img.Repository,
			img.Tag,
			fmt.Sprintf("%d", img.PodCount),
		})
	}
	_ = writer.Write([]string{""})

	// Security
	_ = writer.Write([]string{"=== SECURITY SUMMARY ==="})
	_ = writer.Write([]string{"Metric", "Value"})
	_ = writer.Write([]string{"Secrets Count", fmt.Sprintf("%d", report.SecurityInfo.Secrets)})
	_ = writer.Write([]string{"Privileged Pods", fmt.Sprintf("%d", report.SecurityInfo.PrivilegedPods)})
	_ = writer.Write([]string{"Host Network Pods", fmt.Sprintf("%d", report.SecurityInfo.HostNetworkPods)})
	_ = writer.Write([]string{"Root Containers", fmt.Sprintf("%d", report.SecurityInfo.RootContainers)})
	_ = writer.Write([]string{""})

	// FinOps Analysis
	_ = writer.Write([]string{"=== FINOPS COST ANALYSIS ==="})
	_ = writer.Write([]string{"Metric", "Value"})
	_ = writer.Write([]string{"Estimated Monthly Cost", fmt.Sprintf("$%.2f", report.FinOpsAnalysis.TotalEstimatedMonthlyCost)})
	_ = writer.Write([]string{"Total CPU Requests", report.FinOpsAnalysis.ResourceEfficiency.TotalCPURequests})
	_ = writer.Write([]string{"Total CPU Limits", report.FinOpsAnalysis.ResourceEfficiency.TotalCPULimits})
	_ = writer.Write([]string{"Total Memory Requests", report.FinOpsAnalysis.ResourceEfficiency.TotalMemoryRequests})
	_ = writer.Write([]string{"Total Memory Limits", report.FinOpsAnalysis.ResourceEfficiency.TotalMemoryLimits})
	_ = writer.Write([]string{"CPU Utilization vs Capacity", fmt.Sprintf("%.1f%%", report.FinOpsAnalysis.ResourceEfficiency.CPURequestsVsCapacity)})
	_ = writer.Write([]string{"Memory Utilization vs Capacity", fmt.Sprintf("%.1f%%", report.FinOpsAnalysis.ResourceEfficiency.MemoryRequestsVsCapacity)})
	_ = writer.Write([]string{"Pods Without Requests", fmt.Sprintf("%d", report.FinOpsAnalysis.ResourceEfficiency.PodsWithoutRequests)})
	_ = writer.Write([]string{"Pods Without Limits", fmt.Sprintf("%d", report.FinOpsAnalysis.ResourceEfficiency.PodsWithoutLimits)})
	_ = writer.Write([]string{""})

	// Cost by Namespace
	if len(report.FinOpsAnalysis.CostByNamespace) > 0 {
		_ = writer.Write([]string{"=== COST BY NAMESPACE ==="})
		_ = writer.Write([]string{"Namespace", "Pod Count", "CPU Requests", "Memory Requests", "Est. Cost/Month", "% of Total"})
		for _, ns := range report.FinOpsAnalysis.CostByNamespace {
			_ = writer.Write([]string{
				ns.Namespace,
				fmt.Sprintf("%d", ns.PodCount),
				ns.CPURequests,
				ns.MemoryRequests,
				fmt.Sprintf("$%.2f", ns.EstimatedCost),
				fmt.Sprintf("%.1f%%", ns.CostPercentage),
			})
		}
		_ = writer.Write([]string{""})
	}

	// Cost Optimization Recommendations
	if len(report.FinOpsAnalysis.CostOptimizations) > 0 {
		_ = writer.Write([]string{"=== COST OPTIMIZATION RECOMMENDATIONS ==="})
		_ = writer.Write([]string{"Priority", "Category", "Description", "Impact", "Est. Saving/Month"})
		for _, opt := range report.FinOpsAnalysis.CostOptimizations {
			_ = writer.Write([]string{
				opt.Priority,
				opt.Category,
				opt.Description,
				opt.Impact,
				fmt.Sprintf("$%.2f", opt.EstimatedSaving),
			})
		}
		_ = writer.Write([]string{""})
	}

	// Security Scan Results
	if report.SecurityScan != nil {
		_ = writer.Write([]string{"=== SECURITY SCAN RESULTS ==="})
		_ = writer.Write([]string{"Overall Score", fmt.Sprintf("%.1f", report.SecurityScan.OverallScore)})
		_ = writer.Write([]string{"Risk Level", report.SecurityScan.RiskLevel})
		_ = writer.Write([]string{"Scan Duration", report.SecurityScan.Duration})
		_ = writer.Write([]string{"Tools Used", strings.Join(report.SecurityScan.ToolsUsed, ", ")})
		_ = writer.Write([]string{""})

		if report.SecurityScan.ImageVulnSummary != nil {
			_ = writer.Write([]string{"--- Image Vulnerabilities ---"})
			_ = writer.Write([]string{"Total Images", fmt.Sprintf("%d", report.SecurityScan.ImageVulnSummary.TotalImages)})
			_ = writer.Write([]string{"Scanned Images", fmt.Sprintf("%d", report.SecurityScan.ImageVulnSummary.ScannedImages)})
			_ = writer.Write([]string{"Vulnerable Images", fmt.Sprintf("%d", report.SecurityScan.ImageVulnSummary.VulnerableImages)})
			_ = writer.Write([]string{"Critical", fmt.Sprintf("%d", report.SecurityScan.ImageVulnSummary.CriticalCount)})
			_ = writer.Write([]string{"High", fmt.Sprintf("%d", report.SecurityScan.ImageVulnSummary.HighCount)})
			_ = writer.Write([]string{"Medium", fmt.Sprintf("%d", report.SecurityScan.ImageVulnSummary.MediumCount)})
			_ = writer.Write([]string{"Low", fmt.Sprintf("%d", report.SecurityScan.ImageVulnSummary.LowCount)})
			_ = writer.Write([]string{""})
		}

		if len(report.SecurityScan.PodSecurityIssues) > 0 {
			_ = writer.Write([]string{"--- Pod Security Issues ---"})
			_ = writer.Write([]string{"Namespace", "Pod", "Issue", "Severity"})
			for _, issue := range report.SecurityScan.PodSecurityIssues {
				_ = writer.Write([]string{issue.Namespace, issue.Pod, issue.Issue, issue.Severity})
			}
			_ = writer.Write([]string{""})
		}

		if len(report.SecurityScan.RBACIssues) > 0 {
			_ = writer.Write([]string{"--- RBAC Issues ---"})
			_ = writer.Write([]string{"Kind", "Name", "Issue", "Severity"})
			for _, issue := range report.SecurityScan.RBACIssues {
				_ = writer.Write([]string{issue.Kind, issue.Name, issue.Issue, issue.Severity})
			}
			_ = writer.Write([]string{""})
		}

		if report.SecurityScan.CISBenchmark != nil {
			_ = writer.Write([]string{"--- CIS Benchmark ---"})
			_ = writer.Write([]string{"Version", report.SecurityScan.CISBenchmark.Version})
			_ = writer.Write([]string{"Score", fmt.Sprintf("%.1f%%", report.SecurityScan.CISBenchmark.Score)})
			_ = writer.Write([]string{"Pass", fmt.Sprintf("%d", report.SecurityScan.CISBenchmark.PassCount)})
			_ = writer.Write([]string{"Fail", fmt.Sprintf("%d", report.SecurityScan.CISBenchmark.FailCount)})
			_ = writer.Write([]string{"Warn", fmt.Sprintf("%d", report.SecurityScan.CISBenchmark.WarnCount)})
			_ = writer.Write([]string{""})
		}

		if len(report.SecurityScan.Recommendations) > 0 {
			_ = writer.Write([]string{"--- Security Recommendations ---"})
			_ = writer.Write([]string{"Priority", "Category", "Title", "Description"})
			for _, rec := range report.SecurityScan.Recommendations {
				_ = writer.Write([]string{
					fmt.Sprintf("%d", rec.Priority),
					rec.Category,
					rec.Title,
					rec.Description,
				})
			}
			_ = writer.Write([]string{""})
		}
	}

	// Warning Events
	if len(report.Events) > 0 {
		_ = writer.Write([]string{"=== WARNING EVENTS ==="})
		_ = writer.Write([]string{"Type", "Reason", "Object", "Message", "Count", "Last Seen"})
		for _, event := range report.Events {
			msg := event.Message
			if len(msg) > 100 {
				msg = msg[:100] + "..."
			}
			_ = writer.Write([]string{
				event.Type,
				event.Reason,
				event.Object,
				msg,
				fmt.Sprintf("%d", event.Count),
				event.LastSeen,
			})
		}
		_ = writer.Write([]string{""})
	}

	// AI Analysis
	if report.AIAnalysis != "" {
		_ = writer.Write([]string{"=== AI ANALYSIS ==="})
		// Split analysis into lines for CSV
		lines := strings.Split(report.AIAnalysis, "\n")
		for _, line := range lines {
			_ = writer.Write([]string{line})
		}
	}

	writer.Flush()
	return buf.Bytes(), writer.Error()
}

// ExportToHTML generates HTML format for PDF conversion
func (rg *ReportGenerator) ExportToHTML(report *ComprehensiveReport) string {
	var sb strings.Builder

	sb.WriteString(`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>K13d Cluster Assessment Report</title>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; color: #333; line-height: 1.6; }
h1 { color: #1a1b26; border-bottom: 3px solid #7aa2f7; padding-bottom: 10px; margin-bottom: 20px; }
h2 { color: #24283b; margin-top: 40px; border-bottom: 2px solid #7aa2f7; padding-bottom: 8px; }
h2 a { color: inherit; text-decoration: none; }
h2 a:hover { color: #7aa2f7; }
h3 { color: #414868; margin-top: 25px; }
table { width: 100%; border-collapse: collapse; margin: 15px 0; font-size: 12px; }
th, td { padding: 10px 12px; text-align: left; border: 1px solid #ddd; }
th { background: #24283b; color: white; font-weight: 600; }
tr:nth-child(even) { background: #f8f9fa; }
tr:hover { background: #e9ecef; }
.metric-card { display: inline-block; background: #f8f9fa; padding: 15px 25px; margin: 10px; border-radius: 8px; text-align: center; border: 1px solid #e0e0e0; }
.metric-value { font-size: 28px; font-weight: bold; color: #7aa2f7; }
.metric-label { font-size: 12px; color: #666; margin-top: 5px; }
.health-score { font-size: 48px; font-weight: bold; color: #28a745; }
.health-score.warning { color: #ffc107; }
.health-score.critical { color: #dc3545; }
.status-pass { color: #28a745; font-weight: bold; }
.status-warn { color: #ffc107; font-weight: bold; }
.status-fail { color: #dc3545; font-weight: bold; }
.status-running { color: #28a745; font-weight: bold; }
.status-pending { color: #ffc107; font-weight: bold; }
.status-failed { color: #dc3545; font-weight: bold; }
.ai-analysis { background: #f8f9fa; border-left: 4px solid #7aa2f7; padding: 20px; margin: 20px 0; white-space: pre-wrap; }
.warning-box { background: #fff3cd; border: 1px solid #ffc107; border-left: 4px solid #ffc107; padding: 12px 15px; margin: 15px 0; border-radius: 4px; }
.info-box { background: #e7f3ff; border: 1px solid #7aa2f7; border-left: 4px solid #7aa2f7; padding: 12px 15px; margin: 15px 0; border-radius: 4px; }
.cost-card { display: inline-block; background: #e8f5e9; padding: 15px 25px; margin: 10px; border-radius: 8px; text-align: center; border: 1px solid #4caf50; }
.cost-value { font-size: 24px; font-weight: bold; color: #2e7d32; }
.cost-label { font-size: 11px; color: #666; margin-top: 5px; }
.priority-high { color: #dc3545; font-weight: bold; }
.priority-medium { color: #ffc107; font-weight: bold; }
.priority-low { color: #28a745; font-weight: bold; }
.savings-badge { background: #28a745; color: white; padding: 3px 10px; border-radius: 4px; font-size: 12px; font-weight: 600; }
.toc { background: #f8f9fa; border: 1px solid #e0e0e0; border-radius: 8px; padding: 20px 30px; margin: 30px 0; }
.toc h3 { margin-top: 0; color: #24283b; border-bottom: 1px solid #ddd; padding-bottom: 10px; }
.toc ul { list-style: none; padding: 0; margin: 0; }
.toc li { padding: 6px 0; }
.toc a { color: #7aa2f7; text-decoration: none; font-weight: 500; }
.toc a:hover { text-decoration: underline; }
.toc .toc-subsection { margin-left: 20px; font-size: 13px; }
.section-number { color: #7aa2f7; font-weight: bold; margin-right: 8px; }
.back-to-top { font-size: 11px; color: #7aa2f7; text-decoration: none; float: right; }
.back-to-top:hover { text-decoration: underline; }
.footer { margin-top: 50px; text-align: center; color: #999; font-size: 11px; padding-top: 20px; border-top: 1px solid #e0e0e0; }
.report-meta { background: #f8f9fa; padding: 15px 20px; border-radius: 8px; margin-bottom: 30px; }
.report-meta p { margin: 5px 0; }
@media print { body { margin: 20px; } .back-to-top { display: none; } }
</style>
</head>
<body>
`)

	// Header
	sb.WriteString(`<h1 id="top">K13d Cluster Assessment Report</h1>`)
	sb.WriteString(`<div class="report-meta">`)
	sb.WriteString(fmt.Sprintf(`<p><strong>Report Generated:</strong> %s</p>`, report.GeneratedAt.Format("2006-01-02 15:04:05 MST")))
	sb.WriteString(fmt.Sprintf(`<p><strong>Generated By:</strong> %s</p>`, report.GeneratedBy))
	sb.WriteString(fmt.Sprintf(`<p><strong>Cluster Version:</strong> %s</p>`, report.ClusterInfo.ServerVersion))
	sb.WriteString(`</div>`)

	// Table of Contents
	sb.WriteString(`<div class="toc">`)
	sb.WriteString(`<h3>Table of Contents</h3>`)
	sb.WriteString(`<ul>`)
	sb.WriteString(`<li><a href="#section-1"><span class="section-number">1.</span> Executive Summary</a></li>`)
	if report.MetricsHistory != nil && len(report.MetricsHistory.ClusterMetrics) > 0 {
		sb.WriteString(`<li><a href="#section-2"><span class="section-number">2.</span> Resource Usage History</a></li>`)
	}
	if report.SecurityScan != nil {
		sb.WriteString(`<li><a href="#section-3"><span class="section-number">3.</span> Security Assessment</a>`)
		sb.WriteString(`<ul class="toc-subsection">`)
		if report.SecurityScan.ImageVulnSummary != nil {
			sb.WriteString(`<li><a href="#section-3-1">3.1 Image Vulnerabilities</a></li>`)
		}
		if len(report.SecurityScan.PodSecurityIssues) > 0 {
			sb.WriteString(`<li><a href="#section-3-2">3.2 Pod Security Issues</a></li>`)
		}
		if len(report.SecurityScan.RBACIssues) > 0 {
			sb.WriteString(`<li><a href="#section-3-3">3.3 RBAC Issues</a></li>`)
		}
		if report.SecurityScan.CISBenchmark != nil {
			sb.WriteString(`<li><a href="#section-3-4">3.4 CIS Benchmark Results</a></li>`)
		}
		if len(report.SecurityScan.Recommendations) > 0 {
			sb.WriteString(`<li><a href="#section-3-5">3.5 Security Recommendations</a></li>`)
		}
		sb.WriteString(`</ul></li>`)
	}
	if report.AIAnalysis != "" {
		sb.WriteString(`<li><a href="#section-4"><span class="section-number">4.</span> AI Analysis</a></li>`)
	}
	sb.WriteString(`<li><a href="#section-5"><span class="section-number">5.</span> Cluster Infrastructure</a>`)
	sb.WriteString(`<ul class="toc-subsection">`)
	sb.WriteString(`<li><a href="#section-5-1">5.1 Nodes</a></li>`)
	sb.WriteString(`<li><a href="#section-5-2">5.2 Namespaces</a></li>`)
	sb.WriteString(`</ul></li>`)
	sb.WriteString(`<li><a href="#section-6"><span class="section-number">6.</span> Workloads</a>`)
	sb.WriteString(`<ul class="toc-subsection">`)
	sb.WriteString(`<li><a href="#section-6-1">6.1 Pods</a></li>`)
	sb.WriteString(`<li><a href="#section-6-2">6.2 Deployments</a></li>`)
	sb.WriteString(`<li><a href="#section-6-3">6.3 Services</a></li>`)
	sb.WriteString(`<li><a href="#section-6-4">6.4 Container Images</a></li>`)
	sb.WriteString(`</ul></li>`)
	sb.WriteString(`<li><a href="#section-7"><span class="section-number">7.</span> FinOps Cost Analysis</a>`)
	sb.WriteString(`<ul class="toc-subsection">`)
	sb.WriteString(`<li><a href="#section-7-1">7.1 Resource Efficiency</a></li>`)
	sb.WriteString(`<li><a href="#section-7-2">7.2 Cost by Namespace</a></li>`)
	sb.WriteString(`<li><a href="#section-7-3">7.3 Optimization Recommendations</a></li>`)
	sb.WriteString(`</ul></li>`)
	sb.WriteString(`<li><a href="#section-8"><span class="section-number">8.</span> Security Summary</a></li>`)
	if len(report.Events) > 0 {
		sb.WriteString(`<li><a href="#section-9"><span class="section-number">9.</span> Warning Events</a></li>`)
	}
	sb.WriteString(`</ul>`)
	sb.WriteString(`</div>`)

	// Section 1: Executive Summary
	sb.WriteString(`<h2 id="section-1"><a href="#section-1"><span class="section-number">1.</span> Executive Summary</a><a href="#top" class="back-to-top">[Back to Top]</a></h2>`)

	// Health Score
	healthClass := ""
	healthStatus := "PASS"
	if report.HealthScore < 70 {
		healthClass = "critical"
		healthStatus = "FAIL"
	} else if report.HealthScore < 90 {
		healthClass = "warning"
		healthStatus = "WARN"
	}
	sb.WriteString(fmt.Sprintf(`<div style="text-align: center; margin: 30px 0;">
<div class="health-score %s">%.0f%%</div>
<div style="color: #666; margin-top: 10px;">Overall Cluster Health Score - <strong class="status-%s">%s</strong></div>
</div>`, healthClass, report.HealthScore, strings.ToLower(healthStatus), healthStatus))

	// Summary Cards
	sb.WriteString(`<div style="text-align: center;">`)
	sb.WriteString(fmt.Sprintf(`<div class="metric-card"><div class="metric-value">%d</div><div class="metric-label">Total Nodes (%d Ready)</div></div>`,
		report.NodeSummary.Total, report.NodeSummary.Ready))
	sb.WriteString(fmt.Sprintf(`<div class="metric-card"><div class="metric-value">%d</div><div class="metric-label">Total Pods (%d Running)</div></div>`,
		report.Workloads.TotalPods, report.Workloads.RunningPods))
	sb.WriteString(fmt.Sprintf(`<div class="metric-card"><div class="metric-value">%d</div><div class="metric-label">Deployments</div></div>`,
		report.Workloads.TotalDeployments))
	sb.WriteString(fmt.Sprintf(`<div class="metric-card"><div class="metric-value">%d</div><div class="metric-label">Services</div></div>`,
		report.Workloads.TotalServices))
	sb.WriteString(fmt.Sprintf(`<div class="metric-card"><div class="metric-value">%d</div><div class="metric-label">Namespaces</div></div>`,
		report.NamespaceSummary.Total))
	sb.WriteString(`</div>`)

	// Section 2: Metrics History (if available)
	if report.MetricsHistory != nil && len(report.MetricsHistory.ClusterMetrics) > 0 {
		sb.WriteString(`<h2 id="section-2"><a href="#section-2"><span class="section-number">2.</span> Resource Usage History</a><a href="#top" class="back-to-top">[Back to Top]</a></h2>`)
		sb.WriteString(`<p>Resource usage trends over the last 24 hours:</p>`)
		sb.WriteString(`<div style="text-align: center; margin: 20px 0;">`)
		sb.WriteString(fmt.Sprintf(`<div class="metric-card"><div class="metric-value">%d</div><div class="metric-label">Data Points</div></div>`,
			report.MetricsHistory.DataPoints))
		sb.WriteString(fmt.Sprintf(`<div class="metric-card"><div class="metric-value">%dm</div><div class="metric-label">Avg CPU</div></div>`,
			report.MetricsHistory.Summary.AvgCPUUsage))
		sb.WriteString(fmt.Sprintf(`<div class="metric-card"><div class="metric-value">%dm</div><div class="metric-label">Max CPU</div></div>`,
			report.MetricsHistory.Summary.MaxCPUUsage))
		sb.WriteString(fmt.Sprintf(`<div class="metric-card"><div class="metric-value">%d MB</div><div class="metric-label">Avg Memory</div></div>`,
			report.MetricsHistory.Summary.AvgMemoryUsage))
		sb.WriteString(fmt.Sprintf(`<div class="metric-card"><div class="metric-value">%d MB</div><div class="metric-label">Max Memory</div></div>`,
			report.MetricsHistory.Summary.MaxMemoryUsage))
		sb.WriteString(`</div>`)

		// Resource usage table (sample every 6th point for readability)
		sb.WriteString(`<table><tr><th>Timestamp</th><th>CPU (millicores)</th><th>Memory (MB)</th><th>Running Pods</th><th>Ready Nodes</th></tr>`)
		for i, point := range report.MetricsHistory.ClusterMetrics {
			if i%6 != 0 && i != len(report.MetricsHistory.ClusterMetrics)-1 {
				continue
			}
			sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%d</td><td>%d</td><td>%d</td><td>%d</td></tr>`,
				point.Timestamp, point.CPUUsage, point.MemoryUsage, point.RunningPods, point.ReadyNodes))
		}
		sb.WriteString(`</table>`)
	}

	// Section 3: Security Assessment (if available)
	if report.SecurityScan != nil {
		riskClass := "status-pass"
		switch report.SecurityScan.RiskLevel {
		case "Critical":
			riskClass = "status-fail"
		case "High":
			riskClass = "status-fail"
		case "Medium":
			riskClass = "status-warn"
		}

		sb.WriteString(`<h2 id="section-3"><a href="#section-3"><span class="section-number">3.</span> Security Assessment</a><a href="#top" class="back-to-top">[Back to Top]</a></h2>`)
		sb.WriteString(`<p>Comprehensive security analysis of the Kubernetes cluster:</p>`)
		sb.WriteString(`<div style="text-align: center; margin: 20px 0;">`)
		sb.WriteString(fmt.Sprintf(`<div class="metric-card"><div class="metric-value">%.0f</div><div class="metric-label">Security Score</div></div>`,
			report.SecurityScan.OverallScore))
		sb.WriteString(fmt.Sprintf(`<div class="metric-card"><div class="metric-value %s">%s</div><div class="metric-label">Risk Level</div></div>`,
			riskClass, report.SecurityScan.RiskLevel))
		sb.WriteString(fmt.Sprintf(`<div class="metric-card"><div class="metric-value">%s</div><div class="metric-label">Scan Duration</div></div>`,
			report.SecurityScan.Duration))
		sb.WriteString(`</div>`)
		sb.WriteString(fmt.Sprintf(`<p><strong>Assessment Tools:</strong> %s</p>`, strings.Join(report.SecurityScan.ToolsUsed, ", ")))

		// 3.1 Image Vulnerabilities
		if report.SecurityScan.ImageVulnSummary != nil && report.SecurityScan.ImageVulnSummary.ScannedImages > 0 {
			sb.WriteString(`<h3 id="section-3-1"><span class="section-number">3.1</span> Image Vulnerabilities</h3>`)
			sb.WriteString(`<table><tr><th>Metric</th><th>Count</th><th>Status</th></tr>`)
			sb.WriteString(fmt.Sprintf(`<tr><td>Total Images</td><td>%d</td><td>-</td></tr>`, report.SecurityScan.ImageVulnSummary.TotalImages))
			sb.WriteString(fmt.Sprintf(`<tr><td>Scanned Images</td><td>%d</td><td>-</td></tr>`, report.SecurityScan.ImageVulnSummary.ScannedImages))
			vulnStatus := "PASS"
			vulnClass := "status-pass"
			if report.SecurityScan.ImageVulnSummary.VulnerableImages > 0 {
				vulnStatus = "WARN"
				vulnClass = "status-warn"
			}
			sb.WriteString(fmt.Sprintf(`<tr><td>Vulnerable Images</td><td>%d</td><td class="%s">%s</td></tr>`, report.SecurityScan.ImageVulnSummary.VulnerableImages, vulnClass, vulnStatus))
			critStatus := "PASS"
			critClass := "status-pass"
			if report.SecurityScan.ImageVulnSummary.CriticalCount > 0 {
				critStatus = "FAIL"
				critClass = "status-fail"
			}
			sb.WriteString(fmt.Sprintf(`<tr><td>Critical Vulnerabilities</td><td>%d</td><td class="%s">%s</td></tr>`, report.SecurityScan.ImageVulnSummary.CriticalCount, critClass, critStatus))
			highStatus := "PASS"
			highClass := "status-pass"
			if report.SecurityScan.ImageVulnSummary.HighCount > 0 {
				highStatus = "FAIL"
				highClass = "status-fail"
			}
			sb.WriteString(fmt.Sprintf(`<tr><td>High Vulnerabilities</td><td>%d</td><td class="%s">%s</td></tr>`, report.SecurityScan.ImageVulnSummary.HighCount, highClass, highStatus))
			sb.WriteString(fmt.Sprintf(`<tr><td>Medium Vulnerabilities</td><td>%d</td><td class="status-warn">INFO</td></tr>`, report.SecurityScan.ImageVulnSummary.MediumCount))
			sb.WriteString(fmt.Sprintf(`<tr><td>Low Vulnerabilities</td><td>%d</td><td>INFO</td></tr>`, report.SecurityScan.ImageVulnSummary.LowCount))
			sb.WriteString(`</table>`)
		}

		// 3.2 Pod Security Issues
		if len(report.SecurityScan.PodSecurityIssues) > 0 {
			sb.WriteString(`<h3 id="section-3-2"><span class="section-number">3.2</span> Pod Security Issues</h3>`)
			sb.WriteString(fmt.Sprintf(`<p>Found <strong>%d</strong> pod security issues:</p>`, len(report.SecurityScan.PodSecurityIssues)))
			sb.WriteString(`<table><tr><th>Namespace</th><th>Pod</th><th>Issue Description</th><th>Severity</th><th>Status</th></tr>`)
			for i, issue := range report.SecurityScan.PodSecurityIssues {
				if i >= 15 {
					sb.WriteString(fmt.Sprintf(`<tr><td colspan="5"><em>... and %d more issues (see full scan for details)</em></td></tr>`, len(report.SecurityScan.PodSecurityIssues)-15))
					break
				}
				sevClass := "status-pass"
				status := "INFO"
				if issue.Severity == "CRITICAL" || issue.Severity == "HIGH" {
					sevClass = "status-fail"
					status = "FAIL"
				} else if issue.Severity == "MEDIUM" {
					sevClass = "status-warn"
					status = "WARN"
				}
				sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td class="%s">%s</td></tr>`,
					issue.Namespace, issue.Pod, issue.Issue, issue.Severity, sevClass, status))
			}
			sb.WriteString(`</table>`)
		}

		// 3.3 RBAC Issues
		if len(report.SecurityScan.RBACIssues) > 0 {
			sb.WriteString(`<h3 id="section-3-3"><span class="section-number">3.3</span> RBAC Issues</h3>`)
			sb.WriteString(fmt.Sprintf(`<p>Found <strong>%d</strong> RBAC configuration issues:</p>`, len(report.SecurityScan.RBACIssues)))
			sb.WriteString(`<table><tr><th>Kind</th><th>Name</th><th>Issue Description</th><th>Severity</th><th>Status</th></tr>`)
			for i, issue := range report.SecurityScan.RBACIssues {
				if i >= 15 {
					sb.WriteString(fmt.Sprintf(`<tr><td colspan="5"><em>... and %d more issues (see full scan for details)</em></td></tr>`, len(report.SecurityScan.RBACIssues)-15))
					break
				}
				sevClass := "status-pass"
				status := "INFO"
				if issue.Severity == "CRITICAL" || issue.Severity == "HIGH" {
					sevClass = "status-fail"
					status = "FAIL"
				} else if issue.Severity == "MEDIUM" {
					sevClass = "status-warn"
					status = "WARN"
				}
				sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td class="%s">%s</td></tr>`,
					issue.Kind, issue.Name, issue.Issue, issue.Severity, sevClass, status))
			}
			sb.WriteString(`</table>`)
		}

		// 3.4 CIS Benchmark
		if report.SecurityScan.CISBenchmark != nil {
			sb.WriteString(`<h3 id="section-3-4"><span class="section-number">3.4</span> CIS Benchmark Results</h3>`)
			sb.WriteString(`<p>CIS Kubernetes Benchmark compliance assessment:</p>`)
			sb.WriteString(`<table><tr><th>Metric</th><th>Value</th><th>Status</th></tr>`)
			sb.WriteString(fmt.Sprintf(`<tr><td>Benchmark Version</td><td>%s</td><td>-</td></tr>`, report.SecurityScan.CISBenchmark.Version))
			sb.WriteString(fmt.Sprintf(`<tr><td>Total Checks</td><td>%d</td><td>-</td></tr>`, report.SecurityScan.CISBenchmark.TotalChecks))
			scoreClass := "status-pass"
			scoreStatus := "PASS"
			if report.SecurityScan.CISBenchmark.Score < 70 {
				scoreClass = "status-fail"
				scoreStatus = "FAIL"
			} else if report.SecurityScan.CISBenchmark.Score < 90 {
				scoreClass = "status-warn"
				scoreStatus = "WARN"
			}
			sb.WriteString(fmt.Sprintf(`<tr><td>Compliance Score</td><td>%.1f%%</td><td class="%s">%s</td></tr>`, report.SecurityScan.CISBenchmark.Score, scoreClass, scoreStatus))
			sb.WriteString(fmt.Sprintf(`<tr><td>Passed Checks</td><td>%d</td><td class="status-pass">PASS</td></tr>`, report.SecurityScan.CISBenchmark.PassCount))
			sb.WriteString(fmt.Sprintf(`<tr><td>Failed Checks</td><td>%d</td><td class="status-fail">FAIL</td></tr>`, report.SecurityScan.CISBenchmark.FailCount))
			sb.WriteString(fmt.Sprintf(`<tr><td>Warning Checks</td><td>%d</td><td class="status-warn">WARN</td></tr>`, report.SecurityScan.CISBenchmark.WarnCount))
			sb.WriteString(`</table>`)
		}

		// 3.5 Security Recommendations
		if len(report.SecurityScan.Recommendations) > 0 {
			sb.WriteString(`<h3 id="section-3-5"><span class="section-number">3.5</span> Security Recommendations</h3>`)
			sb.WriteString(`<p>Prioritized security improvement recommendations:</p>`)
			sb.WriteString(`<table><tr><th>Priority</th><th>Category</th><th>Recommendation</th><th>Impact</th></tr>`)
			for _, rec := range report.SecurityScan.Recommendations {
				prioClass := "status-pass"
				if rec.Priority <= 2 {
					prioClass = "status-fail"
				} else if rec.Priority <= 3 {
					prioClass = "status-warn"
				}
				sb.WriteString(fmt.Sprintf(`<tr><td class="%s">P%d</td><td>%s</td><td>%s</td><td>%s</td></tr>`,
					prioClass, rec.Priority, rec.Category, rec.Title, rec.Impact))
			}
			sb.WriteString(`</table>`)
		}
	}

	// Section 4: AI Analysis (if available)
	if report.AIAnalysis != "" {
		sb.WriteString(`<h2 id="section-4"><a href="#section-4"><span class="section-number">4.</span> AI Analysis</a><a href="#top" class="back-to-top">[Back to Top]</a></h2>`)
		sb.WriteString(`<p>AI-powered cluster analysis and recommendations:</p>`)
		sb.WriteString(fmt.Sprintf(`<div class="ai-analysis">%s</div>`, report.AIAnalysis))
	}

	// Section 5: Cluster Infrastructure
	sb.WriteString(`<h2 id="section-5"><a href="#section-5"><span class="section-number">5.</span> Cluster Infrastructure</a><a href="#top" class="back-to-top">[Back to Top]</a></h2>`)

	// 5.1 Nodes
	sb.WriteString(`<h3 id="section-5-1"><span class="section-number">5.1</span> Nodes</h3>`)
	sb.WriteString(fmt.Sprintf(`<p>Total: <strong>%d</strong> nodes (%d Ready, %d Not Ready)</p>`, report.NodeSummary.Total, report.NodeSummary.Ready, report.NodeSummary.NotReady))
	sb.WriteString(`<table><tr><th>Name</th><th>Status</th><th>Roles</th><th>Version</th><th>CPU Capacity</th><th>Memory Capacity</th><th>Internal IP</th></tr>`)
	for _, node := range report.Nodes {
		statusClass := "status-pass"
		status := "Ready"
		if node.Status != "Ready" {
			statusClass = "status-fail"
			status = node.Status
		}
		sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td class="%s">%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>`,
			node.Name, statusClass, status, strings.Join(node.Roles, ", "), node.KubeletVersion, node.CPUCapacity, node.MemoryCapacity, node.InternalIP))
	}
	sb.WriteString(`</table>`)

	// 5.2 Namespaces
	sb.WriteString(`<h3 id="section-5-2"><span class="section-number">5.2</span> Namespaces</h3>`)
	sb.WriteString(fmt.Sprintf(`<p>Total: <strong>%d</strong> namespaces (%d Active)</p>`, report.NamespaceSummary.Total, report.NamespaceSummary.Active))
	sb.WriteString(`<table><tr><th>Name</th><th>Status</th><th>Pods</th><th>Deployments</th><th>Services</th></tr>`)
	for _, ns := range report.Namespaces {
		sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%s</td><td>%d</td><td>%d</td><td>%d</td></tr>`,
			ns.Name, ns.Status, ns.PodCount, ns.DeployCount, ns.ServiceCount))
	}
	sb.WriteString(`</table>`)

	// Section 6: Workloads
	sb.WriteString(`<h2 id="section-6"><a href="#section-6"><span class="section-number">6.</span> Workloads</a><a href="#top" class="back-to-top">[Back to Top]</a></h2>`)

	// 6.1 Pods (limit to first 50 for readability)
	sb.WriteString(`<h3 id="section-6-1"><span class="section-number">6.1</span> Pods</h3>`)
	sb.WriteString(fmt.Sprintf(`<p>Total: <strong>%d</strong> pods (%d Running, %d Pending, %d Failed)</p>`,
		report.Workloads.TotalPods, report.Workloads.RunningPods, report.Workloads.PendingPods, report.Workloads.FailedPods))
	if len(report.Pods) > 50 {
		sb.WriteString(fmt.Sprintf(`<p><em>Showing first 50 of %d pods</em></p>`, len(report.Pods)))
	}
	sb.WriteString(`<table><tr><th>Name</th><th>Namespace</th><th>Status</th><th>Ready</th><th>Restarts</th><th>Node</th><th>Age</th></tr>`)
	for i, pod := range report.Pods {
		if i >= 50 {
			break
		}
		statusClass := "status-pass"
		switch pod.Status {
		case "Pending":
			statusClass = "status-warn"
		case "Failed", "CrashLoopBackOff", "Error":
			statusClass = "status-fail"
		}
		sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%s</td><td class="%s">%s</td><td>%s</td><td>%d</td><td>%s</td><td>%s</td></tr>`,
			pod.Name, pod.Namespace, statusClass, pod.Status, pod.Ready, pod.Restarts, pod.Node, pod.Age))
	}
	sb.WriteString(`</table>`)

	// 6.2 Deployments
	sb.WriteString(`<h3 id="section-6-2"><span class="section-number">6.2</span> Deployments</h3>`)
	sb.WriteString(fmt.Sprintf(`<p>Total: <strong>%d</strong> deployments (%d Healthy)</p>`, report.Workloads.TotalDeployments, report.Workloads.HealthyDeploys))
	sb.WriteString(`<table><tr><th>Name</th><th>Namespace</th><th>Ready</th><th>Up-to-date</th><th>Available</th><th>Strategy</th><th>Age</th></tr>`)
	for _, dep := range report.Deployments {
		sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%s</td><td>%s</td><td>%d</td><td>%d</td><td>%s</td><td>%s</td></tr>`,
			dep.Name, dep.Namespace, dep.Ready, dep.UpToDate, dep.Available, dep.Strategy, dep.Age))
	}
	sb.WriteString(`</table>`)

	// 6.3 Services
	sb.WriteString(`<h3 id="section-6-3"><span class="section-number">6.3</span> Services</h3>`)
	sb.WriteString(fmt.Sprintf(`<p>Total: <strong>%d</strong> services</p>`, report.Workloads.TotalServices))
	sb.WriteString(`<table><tr><th>Name</th><th>Namespace</th><th>Type</th><th>Cluster IP</th><th>External IP</th><th>Ports</th></tr>`)
	for _, svc := range report.Services {
		sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>`,
			svc.Name, svc.Namespace, svc.Type, svc.ClusterIP, svc.ExternalIP, svc.Ports))
	}
	sb.WriteString(`</table>`)

	// 6.4 Container Images
	sb.WriteString(`<h3 id="section-6-4"><span class="section-number">6.4</span> Container Images</h3>`)
	sb.WriteString(fmt.Sprintf(`<p>Total: <strong>%d</strong> unique images in use</p>`, len(report.Images)))
	sb.WriteString(`<table><tr><th>Repository</th><th>Tag</th><th>Pod Count</th></tr>`)
	for i, img := range report.Images {
		if i >= 25 {
			sb.WriteString(fmt.Sprintf(`<tr><td colspan="3"><em>... and %d more images</em></td></tr>`, len(report.Images)-25))
			break
		}
		sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%s</td><td>%d</td></tr>`,
			img.Repository, img.Tag, img.PodCount))
	}
	sb.WriteString(`</table>`)

	// Section 7: FinOps Cost Analysis
	sb.WriteString(`<h2 id="section-7"><a href="#section-7"><span class="section-number">7.</span> FinOps Cost Analysis</a><a href="#top" class="back-to-top">[Back to Top]</a></h2>`)
	sb.WriteString(`<p>Resource cost analysis and optimization opportunities:</p>`)
	sb.WriteString(`<div style="text-align: center; margin: 20px 0;">`)
	sb.WriteString(fmt.Sprintf(`<div class="cost-card"><div class="cost-value">$%.2f</div><div class="cost-label">Est. Monthly Cost</div></div>`,
		report.FinOpsAnalysis.TotalEstimatedMonthlyCost))
	sb.WriteString(fmt.Sprintf(`<div class="cost-card"><div class="cost-value">%.1f%%</div><div class="cost-label">CPU Utilization</div></div>`,
		report.FinOpsAnalysis.ResourceEfficiency.CPURequestsVsCapacity))
	sb.WriteString(fmt.Sprintf(`<div class="cost-card"><div class="cost-value">%.1f%%</div><div class="cost-label">Memory Utilization</div></div>`,
		report.FinOpsAnalysis.ResourceEfficiency.MemoryRequestsVsCapacity))
	sb.WriteString(`</div>`)

	// 7.1 Resource Efficiency
	sb.WriteString(`<h3 id="section-7-1"><span class="section-number">7.1</span> Resource Efficiency</h3>`)
	sb.WriteString(`<table><tr><th>Metric</th><th>Value</th><th>Status</th></tr>`)
	sb.WriteString(fmt.Sprintf(`<tr><td>Total CPU Requests</td><td>%s</td><td>-</td></tr>`, report.FinOpsAnalysis.ResourceEfficiency.TotalCPURequests))
	sb.WriteString(fmt.Sprintf(`<tr><td>Total CPU Limits</td><td>%s</td><td>-</td></tr>`, report.FinOpsAnalysis.ResourceEfficiency.TotalCPULimits))
	sb.WriteString(fmt.Sprintf(`<tr><td>Total Memory Requests</td><td>%s</td><td>-</td></tr>`, report.FinOpsAnalysis.ResourceEfficiency.TotalMemoryRequests))
	sb.WriteString(fmt.Sprintf(`<tr><td>Total Memory Limits</td><td>%s</td><td>-</td></tr>`, report.FinOpsAnalysis.ResourceEfficiency.TotalMemoryLimits))
	reqStatus := "PASS"
	reqClass := "status-pass"
	if report.FinOpsAnalysis.ResourceEfficiency.PodsWithoutRequests > 0 {
		reqStatus = "WARN"
		reqClass = "status-warn"
	}
	sb.WriteString(fmt.Sprintf(`<tr><td>Pods Without Requests</td><td>%d</td><td class="%s">%s</td></tr>`, report.FinOpsAnalysis.ResourceEfficiency.PodsWithoutRequests, reqClass, reqStatus))
	limStatus := "PASS"
	limClass := "status-pass"
	if report.FinOpsAnalysis.ResourceEfficiency.PodsWithoutLimits > 0 {
		limStatus = "WARN"
		limClass = "status-warn"
	}
	sb.WriteString(fmt.Sprintf(`<tr><td>Pods Without Limits</td><td>%d</td><td class="%s">%s</td></tr>`, report.FinOpsAnalysis.ResourceEfficiency.PodsWithoutLimits, limClass, limStatus))
	sb.WriteString(`</table>`)

	// 7.2 Cost by Namespace
	if len(report.FinOpsAnalysis.CostByNamespace) > 0 {
		sb.WriteString(`<h3 id="section-7-2"><span class="section-number">7.2</span> Cost by Namespace</h3>`)
		sb.WriteString(`<table><tr><th>Namespace</th><th>Pods</th><th>CPU Requests</th><th>Memory Requests</th><th>Est. Cost/Month</th><th>% of Total</th></tr>`)
		for i, ns := range report.FinOpsAnalysis.CostByNamespace {
			if i >= 15 {
				sb.WriteString(fmt.Sprintf(`<tr><td colspan="6"><em>... and %d more namespaces</em></td></tr>`, len(report.FinOpsAnalysis.CostByNamespace)-15))
				break
			}
			sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%d</td><td>%s</td><td>%s</td><td>$%.2f</td><td>%.1f%%</td></tr>`,
				ns.Namespace, ns.PodCount, ns.CPURequests, ns.MemoryRequests, ns.EstimatedCost, ns.CostPercentage))
		}
		sb.WriteString(`</table>`)
	}

	// 7.3 Cost Optimization Recommendations
	if len(report.FinOpsAnalysis.CostOptimizations) > 0 {
		totalSavings := 0.0
		for _, opt := range report.FinOpsAnalysis.CostOptimizations {
			totalSavings += opt.EstimatedSaving
		}
		sb.WriteString(`<h3 id="section-7-3"><span class="section-number">7.3</span> Optimization Recommendations</h3>`)
		sb.WriteString(fmt.Sprintf(`<p><strong>Total Potential Savings:</strong> <span class="savings-badge">$%.2f/month</span></p>`, totalSavings))
		sb.WriteString(`<table><tr><th>Priority</th><th>Category</th><th>Recommendation</th><th>Impact</th><th>Est. Savings</th></tr>`)
		for _, opt := range report.FinOpsAnalysis.CostOptimizations {
			priorityClass := "priority-" + opt.Priority
			sb.WriteString(fmt.Sprintf(`<tr><td class="%s">%s</td><td>%s</td><td>%s</td><td>%s</td><td>$%.2f</td></tr>`,
				priorityClass, strings.ToUpper(opt.Priority), opt.Category, opt.Description, opt.Impact, opt.EstimatedSaving))
		}
		sb.WriteString(`</table>`)
	}

	// Section 8: Security Summary
	sb.WriteString(`<h2 id="section-8"><a href="#section-8"><span class="section-number">8.</span> Security Summary</a><a href="#top" class="back-to-top">[Back to Top]</a></h2>`)
	if report.SecurityInfo.PrivilegedPods > 0 || report.SecurityInfo.HostNetworkPods > 0 || report.SecurityInfo.RootContainers > 0 {
		sb.WriteString(`<div class="warning-box"><strong>Warning:</strong> Security concerns detected - review privileged pods and root containers</div>`)
	}
	sb.WriteString(`<table><tr><th>Security Metric</th><th>Count</th><th>Status</th></tr>`)
	sb.WriteString(fmt.Sprintf(`<tr><td>Total Secrets</td><td>%d</td><td>INFO</td></tr>`, report.SecurityInfo.Secrets))
	sb.WriteString(fmt.Sprintf(`<tr><td>Service Accounts</td><td>%d</td><td>INFO</td></tr>`, report.SecurityInfo.ServiceAccounts))
	sb.WriteString(fmt.Sprintf(`<tr><td>Roles</td><td>%d</td><td>INFO</td></tr>`, report.SecurityInfo.Roles))
	sb.WriteString(fmt.Sprintf(`<tr><td>RoleBindings</td><td>%d</td><td>INFO</td></tr>`, report.SecurityInfo.RoleBindings))
	sb.WriteString(fmt.Sprintf(`<tr><td>ClusterRoles</td><td>%d</td><td>INFO</td></tr>`, report.SecurityInfo.ClusterRoles))
	sb.WriteString(fmt.Sprintf(`<tr><td>ClusterRoleBindings</td><td>%d</td><td>INFO</td></tr>`, report.SecurityInfo.ClusterRoleBindings))
	privStatus := "PASS"
	privClass := "status-pass"
	if report.SecurityInfo.PrivilegedPods > 0 {
		privStatus = "FAIL"
		privClass = "status-fail"
	}
	sb.WriteString(fmt.Sprintf(`<tr><td>Privileged Pods</td><td>%d</td><td class="%s">%s</td></tr>`, report.SecurityInfo.PrivilegedPods, privClass, privStatus))
	hostStatus := "PASS"
	hostClass := "status-pass"
	if report.SecurityInfo.HostNetworkPods > 0 {
		hostStatus = "WARN"
		hostClass = "status-warn"
	}
	sb.WriteString(fmt.Sprintf(`<tr><td>Host Network Pods</td><td>%d</td><td class="%s">%s</td></tr>`, report.SecurityInfo.HostNetworkPods, hostClass, hostStatus))
	rootStatus := "PASS"
	rootClass := "status-pass"
	if report.SecurityInfo.RootContainers > 0 {
		rootStatus = "WARN"
		rootClass = "status-warn"
	}
	sb.WriteString(fmt.Sprintf(`<tr><td>Root Containers</td><td>%d</td><td class="%s">%s</td></tr>`, report.SecurityInfo.RootContainers, rootClass, rootStatus))
	sb.WriteString(`</table>`)

	// Section 9: Warning Events
	if len(report.Events) > 0 {
		sb.WriteString(`<h2 id="section-9"><a href="#section-9"><span class="section-number">9.</span> Warning Events</a><a href="#top" class="back-to-top">[Back to Top]</a></h2>`)
		sb.WriteString(fmt.Sprintf(`<p>Recent warning events in the cluster (%d total):</p>`, len(report.Events)))
		sb.WriteString(`<table><tr><th>Reason</th><th>Object</th><th>Message</th><th>Count</th></tr>`)
		for i, event := range report.Events {
			if i >= 25 {
				sb.WriteString(fmt.Sprintf(`<tr><td colspan="4"><em>... and %d more events</em></td></tr>`, len(report.Events)-25))
				break
			}
			msg := event.Message
			if len(msg) > 100 {
				msg = msg[:100] + "..."
			}
			sb.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%s</td><td>%s</td><td>%d</td></tr>`,
				event.Reason, event.Object, msg, event.Count))
		}
		sb.WriteString(`</table>`)
	}

	// Footer
	sb.WriteString(`<div class="footer">`)
	sb.WriteString(`<p>Generated by K13d - AI-Powered Kubernetes Dashboard</p>`)
	sb.WriteString(fmt.Sprintf(`<p>Report generated on %s</p>`, report.GeneratedAt.Format("2006-01-02 15:04:05 MST")))
	sb.WriteString(`</div>`)
	sb.WriteString(`</body></html>`)

	return sb.String()
}

// HandleReports handles report-related API requests
